name: \U0001F41E Bug report
description: Create a report to help us improve Lemmy
title: "[Bug] "
labels: [bug]
assignees: []
body:
  - type: markdown
    attributes:
    value: |
      # Note
      For backend issues, use [lemmy](https://github.com/LemmyNet/lemmy)
  - type: textarea
    id: problem
    attributes:
      label: Issue summary
      description: A summary of the bug.
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Steps to reproduce
      description: |
        1. (for example) I clicked login, and an endless spinner show up.
        2. I tried to install lemmy via this guide, and I'm getting this error.
        3. ...
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Technical details
      description: |
      "- Please post your log: `sudo docker-compose logs > lemmy_log.out`."
      - What OS are you trying to install lemmy on?
      - Any browser console errors?
